// autogenerated and mostly unchanged,
// except for (svelte-)inspector config and adapter

import adapter from "@sveltejs/adapter-node";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

/** @type {import("@sveltejs/kit").Config} */
const config = {
    extensions: [".svelte"],
    // Consult https://kit.svelte.dev/docs/integrations#preprocessors
    // for more information about preprocessors
    preprocess: [vitePreprocess()],

    vitePlugin: {
        // inspect svelte components in running app
        inspector: {
            toggleKeyCombo: "control-alt-i",
            showToggleButton: "never",
        },
    },
    kit: {
        // We can't use the auto adapter since we want to use the node server
        // adapter, which is not supported by auto adapter.
        // https://kit.svelte.dev/docs/adapter-node
        adapter: adapter(),
    },
};
export default config;
