// autogenerated and mostly unchanged,
// except for darkMode config

import { join } from "path";

import { skeleton } from "@skeletonlabs/tw-plugin";
/** @type {import('tailwindcss').Config} */
export default {
    // use skeleton dark mode toggle
    // https://www.skeleton.dev/docs/dark-mode
    darkMode: "selector",
    content: [
        "./src/**/*.{html,js,svelte,ts}",
        join(
            require.resolve("@skeletonlabs/skeleton"),
            "../**/*.{html,js,svelte,ts}",
        ),
    ],
    theme: {
        extend: {},
    },
    plugins: [
        skeleton({
            themes: {
                preset: [
                    {
                        name: "skeleton",
                        enhancements: true,
                    },
                ],
            },
        }),
    ],
};
