// autogenerated and mostly unchanged,
// except for darkMode config and custom color theme

import { customColorTheme } from "./custom-color-theme";

import { join } from "path";

import forms from "@tailwindcss/forms";
import { skeleton } from "@skeletonlabs/tw-plugin";

/** @type {import("tailwindcss").Config} */
export default {
    // https://www.skeleton.dev/docs/dark-mode
    content: [
        "./src/**/*.{html,js,svelte,ts}",
        join(
            require.resolve("@skeletonlabs/skeleton"),
            "../**/*.{html,js,svelte,ts}",
        ),
    ],
    theme: {
        extend: {},
    },
    plugins: [
        forms,
        skeleton({
            themes: {
                custom: [customColorTheme],
            },
        }),
    ],
};
